apiVersion: v1
kind: Service
metadata:
  name: {{ include "mydbpchart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
      nodePort: {{ .Values.serviceNodePort }}
  selector:
    app: {{ template "mydbpchart.fullname" . }}
  type: LoadBalancer
